name: Deploy Hugo site to Pages
on:
 push:
   branches:
     - master
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Install Hugo CLI
       run: |
         wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.137.1/hugo_extended_0.137.1_linux-amd64.deb \
         && sudo dpkg -i hugo.deb
     - name: Build with Hugo
       run: hugo --gc --minify --baseURL "${{ github.repository_owner }}.github.io"
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3.8.0
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./public